### ISSUE TITLE
Unexpected error while opening Steam Boiler when Quark installed

### ISSUE THREAD

**Issue by Tander** [CD4017BE/CD4017BE_lib#3]
Unexpected error while opening Steam Boiler when Quark mod is installed:

http://pastebin.com/M8H2Ws3P

I know that is cross-mod incompatibility, but i don't know whose fault it is.

**Comment by Vazkii** [comment]
https://github.com/CD4017BE/CD4017BE_lib/blob/102ed55875f710d301e26c2dfd1af3978439d7cf/src/java/cd4017be/lib/ModTileEntity.java#L161-L164

This is not how obfuscation works. It may compile, because the function is present at compile time, but it won't be obfuscated, thus the game will throw the crash above. You need to put this in the class that it's actually used in. If you have other uses from it outside of IInventory make another function.

**Comment by CD4017BE** [comment]
fixed: https://github.com/CD4017BE/CD4017BE_lib/commit/ede9dcd397d25f582ddf8d7e4f0a49b08e82ac62

**Comment by Tander** [comment]
Still crashes.
http://pastebin.com/MW2vBT2V

Quark-beta-29
InductiveAutomation-1.9.4-5.1.0

**Comment by Vazkii** [comment]
Same issue somewhere. Look on MCPBot for what it is and override it properly.
